### PR TITLE
Add changes to support URIs with path to changelog

### PR DESCRIPTION
**Pull request by polmiro**
Could we release a version with this update? There's no workaround I can take other than forking and have a custom version in private gem repository (I'm building another gem that uses this one).

### CODE REVIEW

**Comment by michaelklishin** [comment]
Yes, I will release a new version within 24 hours.

**Comment by polmiro** [comment]
Awesome, thanks so much for being so fast :+1:

**Comment by michaelklishin** [comment]
@polmiro 1.5.0 is up on rubygems.org.

**Comment by polmiro** [comment]
Great thanks!

**Pull request merged**
